common: |
  *

get-n: |
  src/utils/getN*.ts

not-get-n: |
  **/*.ts
  !src/utils/getN*.ts

not-get-n-but-number: |
  **/*.ts
  !src/utils/getN*.ts
  **Number*

nothing-to-match: |
  src/components/**
