name: Dump context

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  dump:
    needs: []
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo '${{ toJSON(github) }}'

  deploy:
    needs:
      - dump
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo '${{ toJSON(github) }}'
