name: Dump context

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  merge_group:
    types:
      - checks_requested
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  dump:
    needs: []
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'echo github context'
        run: echo '${{ toJSON(github) }}'

  changes:
    needs: []
    if: ${{ contains(fromJSON('["merge_group", "pull_request"]'), github.event_name) }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
       get-n: ${{ steps.results.outputs.get-n_any_changed }}
       not-get-n: ${{ steps.results.outputs.not-get-n_any_changed }}
       nothing-to-match: ${{ steps.results.outputs.nothing-to-match_any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: tj-actions/changed-files@v45
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          skip_initial_fetch: 'true'
          files_yaml_from_source_file: '.github/configurations/files-changed.yaml'
        id: results

      - name: Results of files changed
        run: |
          echo "${{ steps.results.outputs.get-n_any_changed }}"
          echo "${{ steps.results.outputs.not-get-n_any_changed }}"
          echo "${{ steps.results.outputs.nothing-to-match_any_changed }}"

  lint:
    needs:
      - changes
      - dump
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: exit 0

  lint-nothing-to-match:
    needs:
      - changes
      - dump
    if: ${{ needs.changes.outputs.nothing-to-match == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: exit 0

  lint-always-fail:
    needs:
      - changes
      - dump
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: exit 1

  lint-status:
    needs:
      - lint
      - lint-nothing-to-match
      - lint-always-fail
    if: ${{ !cancelled() && !failure() }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: exit 0
