name: Dump context

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  dump:
    needs: []
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'echo github context'
        run: echo '${{ toJSON(github) }}'

  files-changed:
    needs: []
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
       get-n-any-changed: ${{ steps.results.outputs.get-n_any_changed }}
       not-get-n-any-changed: ${{ steps.results.outputs.not-get-n_any_changed }}
       nothing-to-match: ${{ steps.results.outputs.nothing-to-match_any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: tj-actions/changed-files@v45
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          skip_initial_fetch: 'true'
          files_yaml_from_source_file: '.github/configurations/files-changed.yaml'
        id: results
